# Data Indexer Service Dockerfile
FROM python:3.11-slim

WORKDIR /app

# TODO: Copy application code

# TODO: Install dependencies

# Set entrypoint to run the data indexer script
ENTRYPOINT ["python", "app.py"]
